### ISSUE TITLE
An error occurred while using the module v8

### ISSUE THREAD

**Issue by Kobee1203** [whelk-io/maven-settings-xml-action#52]
I tried to use the module in my Github Workflow but an error occurs while running the job : `Cannot find module '@actions/core'`

Here are the logs:
```
Create Maven Settings
    JAVA_HOME_8.0.252_x64: /opt/hostedtoolcache/jdk/8.0.252/x64
Run whelk-io/maven-settings-xml-action@v8
  with:
    servers: [ { "id": "ossrh", "username": "***", "password": "***" }, { "id": "github", "username": "***", "password": "***" } ]
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.252/x64
    JAVA_HOME_8.0.252_x64: /opt/hostedtoolcache/jdk/8.0.252/x64
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/whelk-io/maven-settings-xml-action/v8/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/whelk-io/maven-settings-xml-action/v8/src/index.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/whelk-io/maven-settings-xml-action/v8/src/index.js'
  ]
}
```

The following is the use of the module in my yml file:
```
     - name: Create Maven Settings
        uses: whelk-io/maven-settings-xml-action@v8
        with:
          servers: '[
            {
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            },
            {
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ github.token }}"
            }
          ]'
```

**Comment by Kobee1203** [comment]
I tried with the previous version v7 and it works fine.

**Comment by zteater** [comment]
Thanks for reporting this @Kobee1203, will take a look.

**Comment by zteater** [comment]
@Kobee1203  this seems to have been cleared up with #53 now tagged as `v9`, can you re-test?

**Comment by zteater** [comment]
Also have delisted `v8` from the marketplace since it was having issues.

**Comment by Kobee1203** [comment]
Ok thanks!

I will test when I will create a new release because I use the module in my Github Release Workflow ;)

**Comment by Kobee1203** [comment]
I tested with `v9` and it works!
Thanks.
